### ISSUE TITLE
A misprint in the .env.sample file

### ISSUE THREAD

**Issue by yesworld** [m-nathani/BitPoint#3]
"development" instead of 

https://github.com/m-nathani/node-typescript-starter/blob/2472d1aa8e2f9cc235b8ba984f7fe56f813f79a4/.env.sample#L2

**Comment by m-nathani** [comment]
@yesworld Thanks.. the issue is [fixed](https://github.com/m-nathani/node-typescript-starter/commit/2472d1aa8e2f9cc235b8ba984f7fe56f813f79a4) now.  
``
